runmode: dev
services: [all] # name of service for run all, maintenance, api, opendata, jobs
port: ":8082"
debug: true
database:
  host: db_host
  port: db_port
  user: db_user
  pass: db_password
  name: db_name
  maxIdle: 50
  maxConn: 100
  automigrate: true
token:
  secret: secret-for-token
email:
  smtp:
    host: smtp_host
    port: smtp_port
    username: smtp_username
    password: smtp_password
  from: email_sender
  domain: for_mailgun_domain # for mail gun only
  apiKey: mailgun_api_key # for mail gun only
  newuser:
    url: url_for_user_set_new_password
  internalRecipients: []
  internalCCRecipients: []
  internalBCCRecipients: []
data:
  url: url_call_data
  apiKey: secret-api-key
  failureMock: true   # use mock data if call data error.
firebase:
  keypath: firebase_key_json
pushTimes: ["08:00", "16:00"] # time for push auto message

#  config for open data
opendata:
  user:
    verify:
      url: url_to_send_in_email_verify
    resetpassword:
      url: url_to_send_in_email_reset_password
  kong:
    url: kong_api_base_url